/*
 * Sherlock - A Minimal Debugger
 * Part of the Sherlock project
 *
 * Copyright (c) 2025-26 Mohammad Shehar Yaar Tausif <sheharyaar48@gmail.com>
 *
 * This file is licensed under the MIT License.
 */

/* Test program generated by ChatGPT along with the Makefile */
#define _GNU_SOURCE
#include <stdio.h>
#include <unistd.h>

__attribute__((noinline)) void local_func(void) { puts("inside local_func"); }

__attribute__((noinline)) void call_printf(const char *msg)
{
	printf("%s\n", msg);
}

__attribute__((noinline)) void call_puts(const char *msg) { puts(msg); }

int main(void)
{
	// triggers lazy binding
	call_puts("first puts");
	call_printf("first printf");

	/* Local symbol call */
	local_func();

	// post-resolution
	call_puts("second puts");
	call_printf("second printf");

	/* Prevent tail-call / exit optimization */
	sleep(1);
	return 0;
}
